from enum import StrEnum

class RoleCode(StrEnum):
    ADMIN = "ADMIN"
    EXECUTOR = "EXECUTOR"
    REGISTRAR = "REGISTRAR"
    CHIEF_REGISTRAR = "CHIEF_REGISTRAR"
    SUB_REGISTRAR = "SUB_REGISTRAR"
    DISTRIBUTOR = "DISTRIBUTOR"
    TREASURER = "TREASURER"

class RequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    REGISTERED = "REGISTERED"
    APPROVED = "APPROVED"
    APPROVED_ON_BEHALF = "APPROVED_ON_BEHALF"
    TO_PAY = "TO_PAY"
    IN_REGISTRY = "IN_REGISTRY"
    APPROVED_FOR_PAYMENT = "APPROVED_FOR_PAYMENT"
    PAID_FULL = "PAID_FULL"
    PAID_PARTIAL = "PAID_PARTIAL"
    REJECTED = "REJECTED"
    DECLINED = "DECLINED"
    RETURNED = "RETURNED"
    CANCELLED = "CANCELLED"
    CLOSED = "CLOSED"
