"""Make article_id nullable in payment_request_lines

Revision ID: 1445c3584beb
Revises: accf77c17244
Create Date: 2025-09-12 12:40:41.268356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1445c3584beb'
down_revision = 'accf77c17244'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_request_lines', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment_request_lines', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
