"""add_split_request_fields_to_payment_requests

Revision ID: 4433e72d60b2
Revises: 1445c3584beb
Create Date: 2025-09-12 15:24:15.105992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433e72d60b2'
down_revision = '1445c3584beb'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('original_request_id', sa.Uuid(), nullable=True))
    op.add_column('payment_requests', sa.Column('split_sequence', sa.Integer(), nullable=True))
    op.add_column('payment_requests', sa.Column('is_split_request', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_foreign_key(None, 'payment_requests', 'payment_requests', ['original_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_column('payment_requests', 'is_split_request')
    op.drop_column('payment_requests', 'split_sequence')
    op.drop_column('payment_requests', 'original_request_id')
    # ### end Alembic commands ###
