"""Add additional contract fields

Revision ID: 4afa58247073
Revises: ac699b6a4981
Create Date: 2025-09-09 19:27:21.362640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4afa58247073'
down_revision = 'ac699b6a4981'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('validity_period', sa.String(length=128), nullable=True))
    op.add_column('contracts', sa.Column('rates', sa.String(length=1000), nullable=True))
    op.add_column('contracts', sa.Column('contract_info', sa.String(length=2000), nullable=True))
    op.add_column('contracts', sa.Column('contract_file_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'contract_file_url')
    op.drop_column('contracts', 'contract_info')
    op.drop_column('contracts', 'rates')
    op.drop_column('contracts', 'validity_period')
    # ### end Alembic commands ###
