"""Add frontend fields to payment_requests

Revision ID: 62c69dc6b9e6
Revises: 803e4ff0c496
Create Date: 2025-09-08 23:39:55.482599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c69dc6b9e6'
down_revision = '803e4ff0c496'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('paying_company', sa.String(length=64), nullable=True))
    op.add_column('payment_requests', sa.Column('counterparty_category', sa.String(length=128), nullable=True))
    op.add_column('payment_requests', sa.Column('vat_rate', sa.String(length=64), nullable=True))
    op.add_column('payment_requests', sa.Column('product_service', sa.String(length=255), nullable=True))
    op.add_column('payment_requests', sa.Column('volume', sa.String(length=128), nullable=True))
    op.add_column('payment_requests', sa.Column('price_rate', sa.String(length=128), nullable=True))
    op.add_column('payment_requests', sa.Column('period', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'period')
    op.drop_column('payment_requests', 'price_rate')
    op.drop_column('payment_requests', 'volume')
    op.drop_column('payment_requests', 'product_service')
    op.drop_column('payment_requests', 'vat_rate')
    op.drop_column('payment_requests', 'counterparty_category')
    op.drop_column('payment_requests', 'paying_company')
    # ### end Alembic commands ###
