"""Add document fields to payment_requests

Revision ID: 803e4ff0c496
Revises: c6b153571ada
Create Date: 2025-09-08 22:50:02.006289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803e4ff0c496'
down_revision = 'c6b153571ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('doc_number', sa.String(length=128), nullable=True))
    op.add_column('payment_requests', sa.Column('doc_date', sa.Date(), nullable=True))
    op.add_column('payment_requests', sa.Column('doc_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'doc_type')
    op.drop_column('payment_requests', 'doc_date')
    op.drop_column('payment_requests', 'doc_number')
    # ### end Alembic commands ###
