"""add_deleted_field_to_payment_requests

Revision ID: 9d343828e9b2
Revises: 4433e72d60b2
Create Date: 2025-09-12 16:15:11.526172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d343828e9b2'
down_revision = '4433e72d60b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'deleted')
    # ### end Alembic commands ###
