"""Add expense_article_text field to payment_requests

Revision ID: c6b153571ada
Revises: 5bb6782e647b
Create Date: 2025-09-08 16:31:04.667092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6b153571ada'
down_revision = '5bb6782e647b'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('expense_article_text', sa.String(length=255), nullable=True))
    # Removed alter_column operations for created_at and updated_at as they don't exist in the table
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'expense_article_text')
    # Removed alter_column operations for created_at and updated_at as they don't exist in the table
    # ### end Alembic commands ###