"""Add REGISTRAR/SUB_REGISTRAR/DISTRIBUTOR workflow models

Revision ID: cb1277e412a8
Revises: 4afa58247073
Create Date: 2025-09-10 20:03:48.664567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1277e412a8'
down_revision = '4afa58247073'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contract_number', sa.String(length=128), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('counterparty_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_request_id', sa.Uuid(), nullable=False),
    sa.Column('expense_article_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('distributor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['expense_article_id'], ['expense_articles.id'], ),
    sa.ForeignKeyConstraint(['original_request_id'], ['payment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_registrar_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('sub_registrar_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'ASSIGNED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['payment_requests.id'], ),
    sa.ForeignKeyConstraint(['sub_registrar_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_registrar_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('sub_registrar_id', sa.Uuid(), nullable=False),
    sa.Column('document_status', sa.String(length=50), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['payment_requests.id'], ),
    sa.ForeignKeyConstraint(['sub_registrar_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distributor_export_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('distributor_request_id', sa.Uuid(), nullable=False),
    sa.Column('export_contract_id', sa.Uuid(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('linked_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['distributor_request_id'], ['distributor_requests.id'], ),
    sa.ForeignKeyConstraint(['export_contract_id'], ['export_contracts.id'], ),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payment_requests', sa.Column('distribution_status', sa.String(length=32), server_default=sa.text("'PENDING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'distribution_status')
    op.drop_table('distributor_export_links')
    op.drop_table('sub_registrar_reports')
    op.drop_table('sub_registrar_assignments')
    op.drop_table('distributor_requests')
    op.drop_table('export_contracts')
    # ### end Alembic commands ###
