"""Add responsible_registrar_id and closing_documents tables

Revision ID: dbaffdb0e4a2
Revises: 62c69dc6b9e6
Create Date: 2025-09-09 17:14:48.606316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaffdb0e4a2'
down_revision = '62c69dc6b9e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closing_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('amount_without_vat', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('original_documents_status', sa.String(length=50), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['payment_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closing_document_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('closing_document_id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['closing_document_id'], ['closing_documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payment_requests', sa.Column('responsible_registrar_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'payment_requests', 'users', ['responsible_registrar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_requests', type_='foreignkey')
    op.drop_column('payment_requests', 'responsible_registrar_id')
    op.drop_table('closing_document_files')
    op.drop_table('closing_documents')
    # ### end Alembic commands ###
