"""add_created_at_and_updated_at_fields_to_dictionaries

Revision ID: e3c094066c3c
Revises: 418b255e4bca
Create Date: 2025-09-11 14:58:25.510102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c094066c3c'
down_revision = '418b255e4bca'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparties', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('counterparties', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('expense_articles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('expense_articles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('vat_rates', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('vat_rates', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vat_rates', 'updated_at')
    op.drop_column('vat_rates', 'created_at')
    op.drop_column('expense_articles', 'updated_at')
    op.drop_column('expense_articles', 'created_at')
    op.drop_column('counterparties', 'updated_at')
    op.drop_column('counterparties', 'created_at')
    # ### end Alembic commands ###
